### PR TITLE
WIP - Remove Linux config, fix paths.

### PR DESCRIPTION
**Pull request by seanknox**
Not sure why Linux support was added here, as Boxen doesn't actually support linux.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
Boxen has partially working Linux support so I think it's not worth deleting this code unless it's known to be broken or is causing other problems.

**Comment by seanknox** [comment]
This is a case of [YAGNI](http://martinfowler.com/bliki/Yagni.html): you ain't gonna need it. Partial support isn't support and introduces unused code that has the cost of maintaining, testing, and working around it. I've never understood various Boxen modules offering "partial Linux support" when Boxen itself isn't supported on Linux. Let's simplify and remove.

**Comment by mikemcquaid** [comment]
Sorry @seanknox, I don't agree here. As I've said before: I don't agree with removing code when a) you don't know if it's unused by users, b) you aren't doing wider refactoring and c) you aren't writing additional tests to verify it's not breaking things.

If you get the chance I'd also like to talk about #58.

**Comment by seanknox** [comment]
Well, we know without a doubt that Boxen is not intended for use on Linux or supported in any way. As has been noted numerous times, none of the (other) maintainers use Linux as their primary operating system, I'm assuming you don't as well. This feature (Linux "support") was added without any tests at all. It should have never been accepted.

Adding a second supported OS adds significant complexity and slows down development on the actual supported OS. There are a number of pull requests at [our-boxen](https://github.com/boxen/our-boxen/search?q=linux&type=Issues&utf8=%E2%9C%93) for Linux support of some kind. They all appear to break support for the original intended OS, aren't completed, and now appear totally abandoned. 

When there is a serious contribution to adding Linux support in some way—with tests—I'm happy to consider it, but short of that, this is dead code.

**Comment by mikemcquaid** [comment]
I feels like we're having a similar discussion to other issues. Obviously this is open-source so you're entitled to work on whatever motivates you but I don't see the benefit in removing code like this as I've said before. There are people working on Linux support (as you linked) and it seems silly to make their life harder for no benefit.

I'm a bit concerned @seanknox that as a Boxen maintainer you seem to be focusing more on removing dead code than testing and merging PRs. If and when a lot of the latter is happening I can see an more argument for the prior.

**Comment by seanknox** [comment]
@mikemcquaid This is one PR I started on a couple months ago and haven't had a chance to revisit. I encourage you to poke around in our-boxen and some of the other Boxen modules—for awhile most of my time was triaging open issues and pull requests, almost exclusively. 

If we agree that simplicity is good, let's agree to leave the system with the simplest design that supports its current functionality and make sure it is well tested. And if we agree that design is good, it is all of our responsibility to make refactoring part and parcel of what we do.

The code proposed to be removed here is—and has never been since its introduction over a year ago—used. And that's my point. YAGNI. When we have actual Linux support, add additional Linux support. When this long abandoned Linux PR https://github.com/boxen/our-boxen/pull/651 is picked up, refactored, no longer breaking Boxen completely, and actually merged in, then I totally support getting more Linux support in Boxen modules.

**Comment by mikemcquaid** [comment]
> The code proposed to be removed here is—and has never been since its introduction over a year ago—used. And that's my point. YAGNI

It's clear you don't need it or want it but it's not clear that no-one else is. I agree we shouldn't be merging Linux PRs without thought but code that's already there has a significantly higher burden on removal as it may be quietly used by someone already. Unfortunately it's impossible to prove either way which is why I'd rather we left it for now.

> This is one PR I started on a couple months ago and haven't had a chance to revisit. I encourage you to poke around in our-boxen and some of the other Boxen modules—for awhile most of my time was triaging open issues and pull requests, almost exclusively.

Yeh, I know you have been doing some great work and that's the area I'd love to direct your focus into. Managing community contributions is the hard part of open-source but the bit that reaps by far the most rewards.

**Comment by dgoodlad** [comment]
Sorry I've been silent on this (and other issues) for so long, but I've been lurking and thought I'd give you the background that seems to be missing here.

Linux support was merged here while @wfarr and I were working on having boxen run in docker containers. It was merged into the branch which was being released as 1.99.x at the time, and never fully considered for general consumption. If it goes, it goes.

@mikemcquaid I 100% buy your "if it ain't broke" argument, and would probably lean towards it. However, I do think that having explicit references to linux support here adds a fair bit of confusion and unnecessary complexity to the module, so I'd be fine with a solid PR to remove it.

**Pull request closed without merging**
