### PR TITLE
Fix executable paths

### PR DESCRIPTION
**Pull request by dgoodlad**

### CODE REVIEW

**Comment by tarebyte** [comment]
@dgoodlad is there we can't merge this PR? Seems to fix a lot of the issues people are having.

**Comment by tarebyte** [comment]
@rafaelfranca do you have an opinion on this?

**Comment by rafaelfranca** [comment]
:shipit:

**Comment by tarebyte** [comment]
@rafaelfranca Minor or Patch revision?

**Comment by rafaelfranca** [comment]
patch, it seems more a bug fix

**Comment by mikemcquaid** [comment]
@tarebyte @rafaelfranca As I only just worked it out today FYI the problem is that all releases except the last two have been made from the `rewrite` branch rather than `master`. I'm going to try and get the rewrite branch merged back today and create a new release on `master`.

**Comment by tarebyte** [comment]
Great thank you @mikemcquaid!

**Pull request merged**
