### PR TITLE
MySQL needs basedir to point to installed location

### LINKED ISSUE #57: FATAL ERROR: Could not find my-default.cnf
Any idea what could cause this?

```
Notice: /Stage[main]/Mysql::Config/Exec[init-mysql-db]/returns: FATAL ERROR: Could not find my-default.cnf
Notice: /Stage[main]/Mysql::Config/Exec[init-mysql-db]/returns:
Notice: /Stage[main]/Mysql::Config/Exec[init-mysql-db]/returns: If you compiled from source, you need to run 'make install' to
Notice: /Stage[main]/Mysql::Config/Exec[init-mysql-db]/returns: copy the software into the correct location ready for operation.
Notice: /Stage[main]/Mysql::Config/Exec[init-mysql-db]/returns:
Notice: /Stage[main]/Mysql::Config/Exec[init-mysql-db]/returns: If you are using a binary release, you must either be at the top
Notice: /Stage[main]/Mysql::Config/Exec[init-mysql-db]/returns: level of the extracted archive, or pass the --basedir option
Notice: /Stage[main]/Mysql::Config/Exec[init-mysql-db]/returns: pointing to that location.
Error: /opt/boxen/homebrew/bin/mysql_install_db       --verbose       --basedir=/opt/boxen/homebrew       --datadir=/opt/boxen/data/mysql       --tmpdir=/tmp returned 1 instead of one of [0]
Error: /Stage[main]/Mysql::Config/Exec[init-mysql-db]/returns: change from notrun to 0 failed: /opt/boxen/homebrew/bin/mysql_install_db       --verbose       --basedir=/opt/boxen/homebrew       --datadir=/opt/boxen/data/mysql       --tmpdir=/tmp returned 1 instead of one of [0]
```

### PR DESCRIPTION
**Pull request by seanknox**
Fixes #57.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@seanknox This isn't correct and breaks things. Did you test a Boxen run with it? `opt/mysql/etc` will never exist.

**Comment by mikemcquaid** [comment]
@seanknox Ping?

**Comment by seanknox** [comment]
I had run Boxen locally as well as ran the tests and everything looked kosher. Been awhile.

**Comment by mikemcquaid** [comment]
Do you have a directory showed by `ls -lha $(brew --prefix mysql)/etc`?

**Pull request merged**
